spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_2
    username: springuser
    password: NewPassword_
  jpa:
    hibernate:
      ddl-auto: create

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

welcome.message: "May the 4th be with you !! "
