spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: springuser
    password: NewThePassword
  jpa:
    hibernate:
      ddl-auto: create

management.security.enabled: true

# management:
#   endpoint:
#     refresh:
#       enabled: true
#     env:
#       enabled: true
#   endpoints:
#     enabled-by-default: true
