spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_1
    username: springuser
    password: ThePassword
  jpa:
    hibernate:
      ddl-auto: create

# management.security.enabled: false

management:
  endpoint:
    refresh:
      enabled: true
    env:
      enabled: true
  endpoints:
    enabled-by-default: true
