spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_2
    username: springuser
    password: NewThePassword
  jpa:
    hibernate:
      ddl-auto: create

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh
