spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: springuser
    password: ThePassword
  jpa:
    hibernate:
      ddl-auto: create

management:
  endpoint:
    refresh:
      enabled: true
    env:
      enabled: true
  endpoints:
    enabled-by-default: true
